apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  index.html: |
    <html>
    <head><title>Hello from Nginx!</title></head>
    <body>
      <h1>Hello from Nginx!</h1>
      <p>Hostname: <strong>{{ .Hostname }}</strong></p>
    </body>
    </html>
